### ISSUE TITLE
Building this amazing tool? :)

### ISSUE THREAD

**Issue by mat-ej** [LPK-Matt/SkidSuite2#2]
Hello,

Thanks for this amazing tool. I have one newbie question, how can I build SkidSuite2 correctly? I can not find any maven pom files or anything about the build process in readme.

Thank you and have a nice day :)

**Comment by LPK-Matt** [comment]
Sorry for the late response, I'm really busy IRL. Anyways there's the releases tab for already compiled builds. As for doing it yourself I honestly have no experience with maven / makefile / etc. so I didn't make any.

**Comment by mat-ej** [comment]
No problem :) Thanks for reply. You happen to know which obfuscator is "Proguard" using?
